<?php

namespace App\Support;

class SiteSettingsCatalog
{
    public static function definitions(): array
    {
        return [
            'store_name' => [
                'type' => 'string',
                'category' => 'brand',
                'default' => 'Angelow',
                'max_length' => 140,
                'label' => 'Nombre de la tienda',
                'hint' => 'Nombre visible en el sitio web y correos.',
                'icon' => 'fa-store',
            ],
            'store_tagline' => [
                'type' => 'string',
                'category' => 'brand',
                'default' => 'Moda con proposito',
                'max_length' => 180,
                'label' => 'Lema de la tienda',
                'hint' => 'Frase corta que describe tu negocio.',
                'icon' => 'fa-tag',
            ],
            'brand_logo' => [
                'type' => 'image',
                'category' => 'brand',
                'default' => '',
                'max_length' => 255,
                'label' => 'Logo de la marca',
                'hint' => 'Sube tu logo en formato PNG, JPG o WEBP.',
                'icon' => 'fa-image',
            ],
            'primary_color' => [
                'type' => 'color',
                'category' => 'brand',
                'default' => '#0077b6',
                'pattern' => '/^#([A-Fa-f0-9]{6})$/',
                'label' => 'Color primario',
                'hint' => 'Color principal de la marca en formato HEX.',
                'icon' => 'fa-palette',
            ],
            'secondary_color' => [
                'type' => 'color',
                'category' => 'brand',
                'default' => '#0f172a',
                'pattern' => '/^#([A-Fa-f0-9]{6})$/',
                'label' => 'Color secundario',
                'hint' => 'Color de apoyo para piezas de marca.',
                'icon' => 'fa-paint-brush',
            ],
            'dashboard_welcome' => [
                'type' => 'string',
                'category' => 'brand',
                'default' => 'Bienvenido al panel',
                'max_length' => 255,
                'label' => 'Mensaje de bienvenida',
                'hint' => 'Título visible en el inicio del dashboard.',
                'icon' => 'fa-door-open',
            ],
            'support_email' => [
                'type' => 'email',
                'category' => 'support',
                'default' => 'soporte@angelow.com',
                'max_length' => 180,
                'label' => 'Correo de soporte',
                'hint' => 'Correo principal para atención al cliente.',
                'icon' => 'fa-envelope',
            ],
            'support_phone' => [
                'type' => 'string',
                'category' => 'support',
                'default' => '+57 300 000 0000',
                'max_length' => 40,
                'label' => 'Teléfono de soporte',
                'hint' => 'Número principal de contacto.',
                'icon' => 'fa-phone',
            ],
            'support_whatsapp' => [
                'type' => 'string',
                'category' => 'support',
                'default' => '+57 300 000 0000',
                'max_length' => 40,
                'label' => 'WhatsApp',
                'hint' => 'Número para atención por WhatsApp.',
                'icon' => 'fa-whatsapp',
            ],
            'support_hours' => [
                'type' => 'string',
                'category' => 'support',
                'default' => 'L-V 8:00 a 18:00',
                'max_length' => 120,
                'label' => 'Horario de atención',
                'hint' => 'Horario visible en la zona de contacto.',
                'icon' => 'fa-clock',
            ],
            'support_address' => [
                'type' => 'string',
                'category' => 'support',
                'default' => 'Medellin, Colombia',
                'max_length' => 240,
                'label' => 'Dirección física',
                'hint' => 'Dirección de la tienda, oficina o bodega.',
                'icon' => 'fa-map-marker-alt',
            ],
            'order_auto_cancel_hours' => [
                'type' => 'int',
                'category' => 'operations',
                'default' => 48,
                'min' => 1,
                'max' => 720,
                'label' => 'Auto cancelar pedidos (horas)',
                'hint' => 'Tiempo máximo antes de cancelar pedidos pendientes.',
                'icon' => 'fa-hourglass-half',
            ],
            'order_review_window_days' => [
                'type' => 'int',
                'category' => 'operations',
                'default' => 15,
                'min' => 1,
                'max' => 60,
                'label' => 'Ventana de reseñas (días)',
                'hint' => 'Días disponibles para dejar una reseña después de comprar.',
                'icon' => 'fa-calendar-alt',
            ],
            'low_stock_threshold' => [
                'type' => 'int',
                'category' => 'operations',
                'default' => 5,
                'min' => 1,
                'max' => 200,
                'label' => 'Umbral de stock bajo',
                'hint' => 'Cantidad mínima para activar alertas de inventario.',
                'icon' => 'fa-box-open',
            ],
            'review_auto_approve' => [
                'type' => 'bool',
                'category' => 'operations',
                'default' => true,
                'label' => 'Auto aprobar reseñas',
                'hint' => 'Publica reseñas automáticamente cuando sea posible.',
                'icon' => 'fa-check-circle',
            ],
            'currency_code' => [
                'type' => 'string',
                'category' => 'operations',
                'default' => 'COP',
                'pattern' => '/^[A-Z]{3}$/',
                'label' => 'Moneda',
                'hint' => 'Código ISO de la moneda. Ejemplo: COP.',
                'icon' => 'fa-money-bill-wave',
            ],
            'analytics_timezone' => [
                'type' => 'string',
                'category' => 'operations',
                'default' => 'America/Bogota',
                'max_length' => 64,
                'label' => 'Zona horaria',
                'hint' => 'Zona horaria usada en reportes y métricas.',
                'icon' => 'fa-globe',
            ],
            'social_instagram' => [
                'type' => 'string',
                'category' => 'social',
                'default' => 'https://instagram.com/angelow',
                'max_length' => 255,
                'label' => 'Instagram',
                'hint' => 'Enlace al perfil de Instagram.',
                'icon' => 'fa-instagram',
            ],
            'social_facebook' => [
                'type' => 'string',
                'category' => 'social',
                'default' => 'https://facebook.com/angelow',
                'max_length' => 255,
                'label' => 'Facebook',
                'hint' => 'Enlace a la página de Facebook.',
                'icon' => 'fa-facebook',
            ],
            'social_tiktok' => [
                'type' => 'string',
                'category' => 'social',
                'default' => '',
                'max_length' => 255,
                'label' => 'TikTok',
                'hint' => 'Enlace al perfil de TikTok.',
                'icon' => 'fa-tiktok',
            ],
            'social_whatsapp' => [
                'type' => 'string',
                'category' => 'social',
                'default' => 'https://wa.me/573000000000',
                'max_length' => 255,
                'label' => 'Enlace de WhatsApp',
                'hint' => 'Enlace directo a WhatsApp.',
                'icon' => 'fa-whatsapp',
            ],
        ];
    }
}