server {
    listen 80;
    listen [::]:80;
    server_name angelow.online;
    charset utf-8;
    client_max_body_size 25m;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    include /etc/nginx/templates/routes.conf;
}
